openapi: 3.0.0
info:
  title: Position Service API
  version: 1.0.0
  description: API for managing user Positions in the bxn-exchange platform.
servers:
  - url: http://localhost:18084
    description: Local server

paths:
  /wallets:
    get:
      summary: Get all wallets
      responses:
        '200':
          description: A list of wallets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Wallet'
    post:
      summary: Create a new wallet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Wallet'
      responses:
        '201':
          description: Wallet created
  /wallets/{id}:
    get:
      summary: Get a wallet by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single wallet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Wallet'
    put:
      summary: Update wallet balance
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: number
              format: float
      responses:
        '200':
          description: Wallet updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Wallet'
    delete:
      summary: Delete a wallet
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Wallet deleted
  /wallets/{id}/debit:
    post:
      summary: Debit a wallet
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: string
      responses:
        '200':
          description: Wallet debited
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Wallet'
  /wallets/{id}/credit:
    post:
      summary: Credit a wallet
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: string
      responses:
        '200':
          description: Wallet credited
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Wallet'
components:
  schemas:
    Wallet:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        balance:
          type: number
          format: float